[package]
name = "hyper-web"
version = "0.1.0"
authors = ["zzzdong <kuwater@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.13"
tokio = {version="0.2", features=["macros", "rt-threaded"]}